### PR TITLE
Make netifaces optional

### PR DESCRIPTION
**Pull request by ofalk**

### CODE REVIEW

**Comment by cygnusb** [comment]
Sorry, but I cannot accept this, since code is intentionally using tabs instead of spaces 
Also mixing this into one pull request is a bad idea.
I am happy to accept the netifaces patch alone (without logging).

**Comment by ofalk** [comment]
OK, I reverted the last commit, however, I'd like to note that pep 8 style guide clearly states one should use 4 spaces per indentation level:
https://www.python.org/dev/peps/pep-0008/#indentation
But it's of course your decision.

**Comment by cygnusb** [comment]
Ok, thanks. PEP8 also states "Tabs should be used solely to remain consistent with code that is already indented with tabs.".
So changing that would also violate PEP8. :-)

**Comment by ofalk** [comment]
@cygnusb Thanks for the merge!
Regarding pep 8, yes, IF there is other code. But nevermind, that - of course - wasn't the important part of my change... :-)

**Pull request merged**
